=== Wetator/wetator/test/xml/dtd/testcase.dtd
<!ELEMENT testcase (step+)>
<!ELEMENT step (#PCDATA | optionalParameter)*>
<!ELEMENT optionalParameter (#PCDATA)>

<!ATTLIST step
    command (Assert_Content | Assert_Deselected | Assert_Disabled | Assert_Selected | Assert_Set | Assert_Title | Click_After_Text | Click_On | Close_Window | Comment | Exec_Java | Go_Back | Mouse_Over | Open_Url | Select | Set | Use_Module) #REQUIRED
    comment (true | false) "false">

=== Wetator/wetator/test/xml/mouse_over.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[mouse_over.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Mouse Over]]></step>
	<step command="Comment"><![CDATA[button is not visible]]></step>
	<step command="Assert_Fail"><![CDATA[Click On, No html element found for 'Submit'.]]><optionalParameter><![CDATA[Submit]]></optionalParameter></step>
	<step command="Comment"><![CDATA[move mouse over the button]]></step>
	<step command="Mouse_Over"><![CDATA[Gurkensalat]]></step>
	<step command="Click_On"><![CDATA[Submit]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, b_plaintext_name, Submit]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[mouse_over.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Mouse Over]]></step>
	<step command="Comment"><![CDATA[button is not visible]]></step>
	<step command="Assert_Fail"><![CDATA[Click On, No html element found for 'Submit'.]]><optionalParameter><![CDATA[Submit]]></optionalParameter></step>
	<step command="Comment"><![CDATA[move mouse over the button]]></step>
	<step command="Mouse_Over"><![CDATA[xt is style]]></step>
	<step command="Click_On"><![CDATA[Submit]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, b_formatedtext_name, Submit]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[mouse_over.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Mouse Over]]></step>
	<step command="Comment"><![CDATA[button is not visible]]></step>
	<step command="Assert_Fail"><![CDATA[Click On, No html element found for 'Submit'.]]><optionalParameter><![CDATA[Submit]]></optionalParameter></step>
	<step command="Comment"><![CDATA[move mouse over the button]]></step>
	<step command="Mouse_Over"><![CDATA[Button will go away]]></step>
	<step command="Click_On"><![CDATA[Submit]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, b_timeout_name, Submit]]></step>
</testcase>

=== Wetator/wetator/test/xml/normalize_command.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[ajax/jquery/jquery_ajax.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with jQuery]]></step>
	<step command="Comment"><![CDATA[blank at start]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with jQuery]]></step>
	<step command="Comment"><![CDATA[blank at end]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with jQuery]]></step>
	<step command="Comment"><![CDATA[blank at start and end]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with jQuery]]></step>
	<step command="Comment"><![CDATA[blanks inside]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with jQuery]]></step>
</testcase>

=== Wetator/wetator/test/xml/select_multipleSelect.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">

<testcase>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect with name</step>
    <step command="Select">multipleSelect_Name[], option2</step>
    <step command="Select">multipleSelect_Name[], option4</step>
    <step command="Click_On">MultipleSelectNameTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_Name, o_value2, o_value4, MultipleSelectNameTest, OK</step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelectOptGroup with name</step>
    <step command="Select">multipleSelectOptgroup_Name[], blue</step>
    <step command="Select">multipleSelectOptgroup_Name[], value1</step>
    <step command="Select">multipleSelectOptgroup_Name[], value2</step>
    <step command="Click_On">MultipleSelectOptGroupNameTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelectOptgroup_Name, o_blue, o_value1, o_value2, MultipleSelectOptGroupNameTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect with id</step>
    <step command="Select">multipleSelect_Id, option3</step>
    <step command="Select">multipleSelect_Id, option4</step>
    <step command="Click_On">MultipleSelectIdTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_Id, o_value3, o_value4, MultipleSelectIdTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect with default selection</step>
    <step command="Select">multipleSelect_NameValue[], option4</step>
    <step command="Select">multipleSelect_NameValue[], option1</step>
    <step command="Click_On">MultipleSelectNameValueTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_NameValue, o_value1, o_value4, MultipleSelectNameValueTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by label</step>
    <step command="Select">MultipleSelect Label, option1</step>
    <step command="Select">MultipleSelect Label, option2</step>
    <step command="Click_On">MultipleSelectLabelTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_Label, o_value1, o_value2,  MultipleSelectLabelTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by layout directly before</step>
    <step command="Select">MultipleSelect LayoutLabel before, option3</step>
    <step command="Select">MultipleSelect LayoutLabel before, option2</step>
    <step command="Click_On">MultipleSelectLayoutBeforeTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_LayoutBefore, o_value2, o_value3, MultipleSelectLayoutBeforeTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by layout directly before formated</step>
    <step command="Select">MultipleSelect LayoutLabel before formated, option2</step>
    <step command="Click_On">MultipleSelectLayoutBeforeFormatedTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_LayoutBeforeFormated, o_value2, MultipleSelectLayoutBeforeFormatedTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by layout at top</step>
    <step command="Select">MultipleSelect LayoutLabel at top, option3</step>
    <step command="Click_On">MultipleSelectLayoutTopTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_LayoutTop, o_value3, MultipleSelectLayoutTopTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by layout at top formated</step>
    <step command="Select">MultipleSelect LayoutLabel at top formated, option4</step>
    <step command="Select">MultipleSelect LayoutLabel at top formated, option1</step>
    <step command="Click_On">MultipleSelectLayoutTopFormatedTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_LayoutTopFormated, o_value1, o_value4, MultipleSelectLayoutTopFormatedTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by layout at left</step>
    <step command="Select">MultipleSelect LayoutLabel at left, option1</step>
    <step command="Select">MultipleSelect LayoutLabel at left, option3</step>
    <step command="Click_On">MultipleSelectLayoutLeftTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_LayoutLeft, o_value1, o_value3, MultipleSelectLayoutLeftTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">select.html</step>
    <step command="Assert_Title">Wetator / Select</step>
    <step command="Comment">MultipleSelect identified by layout at left formated</step>
    <step command="Select">MultipleSelect LayoutLabel at left formated, option2</step>
    <step command="Select">MultipleSelect LayoutLabel at left formated, option4</step>
    <step command="Click_On">MultipleSelectLayoutLeftFormatedTest</step>
    <step command="Assert_Content">GET Parameters, Key, Value, multipleSelect_LayoutLeftFormated, o_value2, o_value4, MultipleSelectLayoutLeftFormatedTest, OK</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Comment"></step>
</testcase>

=== Wetator/wetator/test/xml/select_radio.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton with name]]></step>
	<step command="Comment"><![CDATA[not possible]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton with id]]></step>
	<step command="Select"><![CDATA[radioId2]]></step>
	<step command="Click_On"><![CDATA[RadioButtonIdTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_Id, r_value2, RadioButtonIdTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton with default selection]]></step>
	<step command="Select"><![CDATA[radioIdValue1]]></step>
	<step command="Click_On"><![CDATA[RadioButtonIdValueTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_IdValue, r_value1, RadioButtonIdValueTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by label]]></step>
	<step command="Select"><![CDATA[Radio2 Label]]></step>
	<step command="Click_On"><![CDATA[RadioButtonLabelTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_Label, r_value2, RadioButtonLabelTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout directly after]]></step>
	<step command="Select"><![CDATA[RadioButton1 LayoutLabel after]]></step>
	<step command="Click_On"><![CDATA[RadioButtonLayoutAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_LayoutAfter, r_value1, RadioButtonLayoutAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout directly after formated]]></step>
	<step command="Select"><![CDATA[RadioButton2 LayoutLabel after formated]]></step>
	<step command="Click_On"><![CDATA[RadioButtonLayoutAfterFormatedTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_LayoutFormatedAfter, r_value2, RadioButtonLayoutAfterFormatedTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout at right]]></step>
	<step command="Select"><![CDATA[RadioButton1 LayoutLabel at right]]></step>
	<step command="Click_On"><![CDATA[RadioButtonLayoutRightTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_LayoutRight, r_value1, RadioButtonLayoutRightTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout at right formated]]></step>
	<step command="Select"><![CDATA[RadioButton2 LayoutLabel right formated]]></step>
	<step command="Click_On"><![CDATA[RadioButtonLayoutRightFormatedTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, radioButton_LayoutRightFormated, r_value2, RadioButtonLayoutRightFormatedTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
</testcase>

=== Wetator/wetator/test/xml/assert_disabled.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[assert_disabled.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Disabled]]></step>
	<step command="Comment"><![CDATA[ ]]></step>
	<step command="Comment"><![CDATA[ ]]></step>
	<step command="Comment"><![CDATA[Text Input]]></step>
	<step command="Comment"><![CDATA[InputText with name]]></step>
	<step command="Assert_Disabled"><![CDATA[inputText_Name]]></step>
	<step command="Comment"><![CDATA[InputText with name]]></step>
	<step command="Assert_Disabled"><![CDATA[inputText_Name]]></step>
	<step command="Comment"><![CDATA[InputText with id]]></step>
	<step command="Assert_Disabled"><![CDATA[inputText_Id]]></step>
	<step command="Comment"><![CDATA[InputText identified by label]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText Label]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout directly before]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel before]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout directly before formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel before formated]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout at top]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel at top]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout at top formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel at top formated]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout at left]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel at left]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout at left formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel at left formated]]></step>
	<step command="Comment"><![CDATA[InputText identified by layout at left formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputText LayoutLabel at left formated]]></step>
	<step command="Comment"><![CDATA[ ]]></step>
	<step command="Comment"><![CDATA[ ]]></step>
	<step command="Comment"><![CDATA[Password Input]]></step>
	<step command="Comment"><![CDATA[InputPassword with name]]></step>
	<step command="Assert_Disabled"><![CDATA[inputPassword_Name]]></step>
	<step command="Comment"><![CDATA[InputPassword with id]]></step>
	<step command="Assert_Disabled"><![CDATA[inputPassword_Id]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by label]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword Label]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by layout directly before]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword LayoutLabel before]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by layout directly before formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword LayoutLabel before formated]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by layout at top]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword LayoutLabel at top]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by layout at top formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword LayoutLabel at top formated]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by layout at left]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword LayoutLabel at left]]></step>
	<step command="Comment"><![CDATA[InputPassword identified by layout at left formated]]></step>
	<step command="Assert_Disabled"><![CDATA[InputPassword LayoutLabel at left formated]]></step>
	<step command="Comment"><![CDATA[ ]]></step>
	<step command="Comment"><![CDATA[ ]]></step>
	<step command="Comment"><![CDATA[TextArea Input]]></step>
	<step command="Comment"><![CDATA[TextArea with name]]></step>
	<step command="Assert_Disabled"><![CDATA[textArea_Name]]></step>
	<step command="Comment"><![CDATA[TextArea with id]]></step>
	<step command="Assert_Disabled"><![CDATA[textArea_Id]]></step>
	<step command="Comment"><![CDATA[TextArea identified by label]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea Label]]></step>
	<step command="Comment"><![CDATA[TextArea identified by layout directly before]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea LayoutLabel before]]></step>
	<step command="Comment"><![CDATA[TextArea identified by layout directly before formated]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea LayoutLabel before formated]]></step>
	<step command="Comment"><![CDATA[TextArea identified by layout at top]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea LayoutLabel at top]]></step>
	<step command="Comment"><![CDATA[TextArea identified by layout at top formated]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea LayoutLabel at top formated]]></step>
	<step command="Comment"><![CDATA[TextArea identified by layout at left]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea LayoutLabel at left]]></step>
	<step command="Comment"><![CDATA[TextArea identified by layout at left formated]]></step>
	<step command="Assert_Disabled"><![CDATA[TextArea LayoutLabel at left formated]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"><![CDATA[Element: Button]]></step>
	<step command="Comment"><![CDATA[Button with Text]]></step>
	<step command="Assert_Disabled"><![CDATA[ButtonWithText]]></step>
	<step command="Comment"><![CDATA[Button with Image alt]]></step>
	<step command="Assert_Disabled"><![CDATA[b_imageTestAlt]]></step>
	<step command="Comment"><![CDATA[Button with Image title]]></step>
	<step command="Assert_Disabled"><![CDATA[b_imageTestTitle]]></step>
	<step command="Comment"><![CDATA[Button with Image src]]></step>
	<step command="Assert_Disabled"><![CDATA[sword2.png]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"><![CDATA[Element: Input]]></step>
	<step command="Comment"><![CDATA[InputType Submit with Value]]></step>
	<step command="Assert_Disabled"><![CDATA[InputTypeSubmit]]></step>
	<step command="Comment"><![CDATA[InputType Button with Value]]></step>
	<step command="Assert_Disabled"><![CDATA[Button]]></step>
	<step command="Comment"><![CDATA[InputType Image with Alt]]></step>
	<step command="Assert_Disabled"><![CDATA[ImageButton]]></step>
	<step command="Comment"><![CDATA[InputType Image with Title]]></step>
	<step command="Assert_Disabled"><![CDATA[ImageButtonTitle]]></step>
	<step command="Comment"><![CDATA[InputType Image with src]]></step>
	<step command="Assert_Disabled"><![CDATA[sword1.png]]></step>
	<step command="Comment"><![CDATA[InputType Radio with id]]></step>
	<step command="Assert_Disabled"><![CDATA[i_r_inputtyperadioid]]></step>
	<step command="Comment"><![CDATA[InputType Radio with name makes no sense]]></step>
	<step command="Comment"><![CDATA[InputType Checkbox with id]]></step>
	<step command="Assert_Disabled"><![CDATA[i_c_inputtypecheckboxid]]></step>
	<step command="Comment"><![CDATA[InputType Checkbox with name]]></step>
	<step command="Assert_Disabled"><![CDATA[i_c_inputtypecheckboxname]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"><![CDATA[Element: Select]]></step>
	<step command="Comment"><![CDATA[SingleSelect with name]]></step>
	<step command="Assert_Disabled"><![CDATA[singleSelect_Name]]></step>
	<step command="Comment"><![CDATA[SingleSelect (incl. OptGroup) with name]]></step>
	<step command="Assert_Disabled"><![CDATA[singleSelectOptGroup_Name]]></step>
	<step command="Comment"><![CDATA[SingleSelect with id]]></step>
	<step command="Assert_Disabled"><![CDATA[singleSelect_Id]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"><![CDATA[Element: OptGroup]]></step>
	<step command="Comment"><![CDATA[Fails in IE 6.0 (Bug)]]></step>
	<step command="Comment"><![CDATA[OptGroup with Label]]></step>
	<step command="Assert_Disabled"><![CDATA[colors]]></step>
	<step command="Comment"><![CDATA[OptGroup with id]]></step>
	<step command="Assert_Disabled"><![CDATA[optgroup_colors]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"><![CDATA[Element: Option]]></step>
	<step command="Comment"><![CDATA[Fails in IE 6.0 (Bug)]]></step>
	<step command="Comment"><![CDATA[Option with id]]></step>
	<step command="Assert_Disabled"><![CDATA[option1]]></step>
	<step command="Comment"><![CDATA[Option (in OptGroup)  with id]]></step>
	<step command="Assert_Disabled"><![CDATA[option_red]]></step>
	<step command="Comment"><![CDATA[test for unused parameter]]></step>
	<step command="Assert_Fail"><![CDATA[Assert Disabled, The command 'Assert Disabled' does not use the value 'unused' provided in column 2.]]><optionalParameter><![CDATA[inputText_Name]]></optionalParameter>
	</step>
</testcase>

=== Wetator/wetator/test/xml/jquery/modal_confirmation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testcase SYSTEM "../dtd/testcase.dtd">

<testcase>
    <step command="Open_Url">js/jquery/modal-confirmation.html</step>
    <step command="Assert_Content">Empty the recycle bin?</step>
    <step command="Click_On">Cancel</step>
    <step command="Assert_Content">Button: Cancel</step>
    <step command="Comment"></step>
    <step command="Open_Url">js/jquery/modal-confirmation.html</step>
    <step command="Assert_Content">Empty the recycle bin?</step>
    <step command="Click_On">Delete all items</step>
    <step command="Assert_Content">Button: Delete all items</step>
</testcase>

=== Wetator/wetator/test/xml/flow_simple_search.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[simple_search.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Simple Search]]></step>
	<step command="Comment"><![CDATA[set selects and fields by label and press the button]]></step>
	<step command="Select"><![CDATA[Field1, >]]></step>
	<step command="Set"><![CDATA[Field1]]><optionalParameter><![CDATA[value1]]></optionalParameter></step>
	<step command="Select"><![CDATA[Field2, <]]></step>
	<step command="Set"><![CDATA[Field2]]><optionalParameter><![CDATA[value2]]></optionalParameter></step>
	<step command="Select"><![CDATA[Field3, =]]></step>
	<step command="Set"><![CDATA[Field3]]><optionalParameter><![CDATA[value3]]></optionalParameter></step>
	<step command="Select"><![CDATA[Field4, >]]></step>
	<step command="Set"><![CDATA[Field4]]><optionalParameter><![CDATA[value4]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[Search]]></step>
	<step command="Assert_Content"><![CDATA[name_field1_select, o2_f1s, name_field1_input, value1, name_field2_select, o3_f2s, name_field2_input, value2, name_field3_select, o1_f3s, name_field3_input, value3, name_field4_select, o2_f4s, name_field4_input, value4]]></step>
</testcase>
