=== Wetator/wetator/test/xml/dtd/testcase.dtd
<!ELEMENT testcase (step+)>
<!ELEMENT step (#PCDATA | optionalParameter)*>
<!ELEMENT optionalParameter (#PCDATA)>

<!ATTLIST step
    command (Assert_Content | Assert_Deselected | Assert_Disabled | Assert_Selected | Assert_Set | Assert_Title | Click_After_Text | Click_On | Close_Window | Comment | Exec_Java | Go_Back | Mouse_Over | Open_Url | Select | Set | Use_Module) #REQUIRED
    comment (true | false) "false">

=== Wetator/wetator/test/xml/assert_content.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">

<testcase>
    <step command="Open_Url">assert_content.html</step>
    <step command="Assert_Content">Wetator / Assert Content</step>
    <step command="Comment">now start the content tests</step>
    <step command="Assert_Content">Wetator / Assert Content</step>
    <step command="Assert_Content">Pferde fressen keinen Gurkensalat.</step>
    <step command="Assert_Content">This text is styled.</step>
    <step command="Assert_Content">Column 1 Column 2</step>
    <step command="Assert_Content">schöne Häuser</step>
    <step command="Assert_Content"><![CDATA[<h:outputText>]]></step>
    <step command="Comment">now search for parts of the text</step>
    <step command="Assert_Content">fressen kei</step>
    <step command="Assert_Content">is text is sty</step>
    <step command="Assert_Content">mn 1</step>
    <step command="Assert_Content">Line1 schön</step>
    <step command="Assert_Content"><![CDATA[putText>]]></step>
    <step command="Comment">some wildcards</step>
    <step command="Assert_Content">W?tator / Assert Content</step>
    <step command="Assert_Content">Pferde*Gurkensalat.</step>
    <step command="Assert_Content">This tex*ed.</step>
    <step command="Assert_Content">Column 1 Column 2****</step>
    <step command="Assert_Content">****schöne Häuser</step>
    <step command="Assert_Content"><![CDATA[<h:outp*utText>]]></step>
    <step command="Comment">search many</step>
    <step command="Assert_Content">Wetator *Plain*Content*Special</step>
    <step command="Comment">now searching with more parts</step>
    <step command="Assert_Content">Pferde,fressen,keinen,Gurkensalat</step>
    <step command="Assert_Content">Pferde, fressen, keinen, Gurkensalat</step>
    <step command="Assert_Fail">Assert Content, Expected content(s) {not found} or [in wrong order]: 'Pferde\, keinen\, [fressen]\, Gurkensalat' (content: 'Wetator Wetator / Assert Content Plain Content Pferde fressen keinen Gurkensalat. Font infos in Content This text is styled. Content in Table Column 1 Column 2 Special Content in Table Line1 schöne Häuser &lt;h:outputText&gt; Image to search in page source Test image alt text Select to check for the options First Option Second Option Another Option Various Content types download.txt wet_test.pdf wet_test.xls unknown_content_type.bin sword4.png').<optionalParameter>Pferde,keinen,fressen,Gurkensalat</optionalParameter></step>
    <step command="Assert_Fail">Assert Content, Expected content(s) {not found} or [in wrong order]: 'Pferde\, fressen\, {meinen}\, Gurkensalat' (content: 'Wetator Wetator / Assert Content Plain Content Pferde fressen keinen Gurkensalat. Font infos in Content This text is styled. Content in Table Column 1 Column 2 Special Content in Table Line1 schöne Häuser &lt;h:outputText&gt; Image to search in page source Test image alt text Select to check for the options First Option Second Option Another Option Various Content types download.txt wet_test.pdf wet_test.xls unknown_content_type.bin sword4.png').<optionalParameter>Pferde, fressen, meinen, Gurkensalat</optionalParameter></step>
    <step command="Comment">options of a select</step>
    <step command="Assert_Content">Select to check for the options, First Option, Second Option, Another Option, Various Content types</step>
    <step command="Comment">error for unused parameter</step>
    <step command="Assert_Fail">Assert Content, The command 'Assert Content' does not use the value 'unused' provided in column 2.<optionalParameter>Pferde,fressen,keinen,Gurkensalat</optionalParameter></step>
    <step command="Comment"></step>
    <step command="Comment">content type text</step>
    <step command="Open_Url">assert_content.html</step>
    <step command="Click_On">download.txt</step>
    <step command="Assert_Content">simple, text, file, WeT</step>
    <step command="Comment">content type pdf</step>
    <step command="Open_Url">assert_content.html</step>
    <step command="Click_On">wet_test.pdf</step>
    <step command="Assert_Content">simple, PDF, file, WeT</step>
    <step command="Comment">content type pdf</step>
    <step command="Open_Url">assert_content.html</step>
    <step command="Click_On">wet_test.xls</step>
    <step command="Assert_Content">[Tab1], Wetator Page 1, [Tab2], Wetator Test Page2 Web application testing is fun</step>
    <step command="Comment">content type not supported</step>
    <step command="Open_Url">assert_content.html</step>
    <step command="Click_On">sword4.png</step>
    <step command="Assert_Fail">Assert Content, Unsupported page type (image/png).<optionalParameter>sword</optionalParameter></step>
    <step command="Comment">unknown content type not supported</step>
    <step command="Open_Url">assert_content.html</step>
    <step command="Click_On">unknown_content_type.bin</step>
    <step command="Assert_Fail">Assert Content, Unsupported page type (application/octet-stream).<optionalParameter>unknown_content_type.bin</optionalParameter></step>
</testcase>

=== Wetator/wetator/test/xml/use_module.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[testcases.html]]></step>
	<step command="Use_Module"><![CDATA[modules/module.xml]]></step>
	<step command="Comment"><![CDATA[after use module]]></step>
	<step command="Comment"></step>
	<step command="Comment"><![CDATA[module with parameter]]></step>
	<step command="Use_Module"><![CDATA[modules/module_with_parameters.xml]]><optionalParameter><![CDATA[assert_content.html, Wetator / Assert Content]]></optionalParameter>
	</step>
</testcase>

=== Wetator/wetator/test/java/org/rbri/wet/test/resource/junit.xml
<?xml version="1.0"?>
<!DOCTYPE testcase SYSTEM "../../../../../xml/dtd/testcase.dtd">
<testcase>
    <step command="Comment">Just a comment</step>
    <step command="Open_Url">set.html</step>
    <step command="Assert_Title">Wetator / Set</step>
    <step command="Set">inputText_Name<optionalParameter>testValue</optionalParameter></step>
    <step command="Click_On">InputTextNameTest</step>
    <step command="Click_On" comment="true">Just another comment</step>
    <step command="Assert_Content">GET Parameters Key Value inputText_Name testValue InputTextNameTest OK</step>
    <step command="Comment"></step>
    <step command="Comment"/>
</testcase>

=== Wetator/wetator/test/xml/go_back.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[simple_login.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Simple Login]]></step>
	<step command="Comment"><![CDATA[set fields by label and press the button]]></step>
	<step command="Set"><![CDATA[User:]]><optionalParameter><![CDATA[WeT]]></optionalParameter></step>
	<step command="Set"><![CDATA[Password:]]><optionalParameter><![CDATA[tew]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[Login]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Request Snoopy]]></step>
	<step command="Assert_Content"><![CDATA[POST Parameters, Key, Value, userid, WeT, password, tew]]></step>
	<step command="Comment"><![CDATA[now we are going back]]></step>
	<step command="Go_Back"></step>
	<step command="Assert_Title"><![CDATA[Wetator / Simple Login]]></step>
	<step command="Assert_Set" comment="true"><![CDATA[User:]]><optionalParameter><![CDATA[WeT]]></optionalParameter></step>
	<step command="Set" comment="true"><![CDATA[Password:]]></step>
	<step command="Assert_Fail"><![CDATA[Go Back, Walking trough the history failed (steps: 1 currentPos: -1 historySize: 2).]]></step>
</testcase>

=== Wetator/wetator/test/xml/anchor_inside_page.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[anchor_inside_page.html#chapter1]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Anchor Inside Page]]></step>
	<step command="Comment"><![CDATA[unknown anchor]]></step>
	<step command="Assert_Fail"><![CDATA[Open Url, No id/anchor found for ref 'unknownAnchor'.]]><optionalParameter><![CDATA[anchor_inside_page.html#unknownAnchor]]></optionalParameter></step>
	<step command="Comment"><![CDATA[duplicate anchor]]></step>
	<step command="Open_Url"><![CDATA[anchor_inside_page.html#duplicteAnchor]]></step>
	<step command="Comment"><![CDATA[click on anchor]]></step>
	<step command="Open_Url"><![CDATA[anchor_inside_page.html]]></step>
	<step command="Click_On"><![CDATA[jump to 'Chapter 1']]></step>
	<step command="Assert_Fail"><![CDATA[Click On, No id/anchor found for ref 'chapter3'.]]><optionalParameter><![CDATA[jump to non existing anchor]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[jump to duplicate anchor]]></step>
	<step command="Comment"><![CDATA[now the javascript game]]></step>
	<step command="Click_On"><![CDATA[open popup and jump to 'Chapter 1']]></step>
	<step command="Close_Window"></step>
	<step command="Assert_Fail"><![CDATA[Click On, No id/anchor found for ref 'chapter3'.]]><optionalParameter><![CDATA[open popup and jump to non existing anchor]]></optionalParameter></step>
	<step command="Close_Window"></step>
	<step command="Click_On"><![CDATA[open popup and jump to duplicate anchor]]></step>
	<step command="Close_Window"></step>
</testcase>

=== Wetator/wetator/test/xml/assert_title.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[assert_content.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Content]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Cont*]]></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Sel*]]></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_content.html]]></step>
	<step command="Comment"><![CDATA[test for warning about unused parameter]]></step>
	<step command="Assert_Fail"><![CDATA[Assert Title, The command 'Assert Title' does not use the value 'unused' provided in column 2.]]><optionalParameter><![CDATA[Wetator / Assert Content]]></optionalParameter></step>
	<step command="Comment"><![CDATA[test for parameter support]]></step>
	<step command="Assert_Title"><![CDATA[${wet} / Assert Content]]></step>
	<step command="Comment"><![CDATA[test for secret parts]]></step>
	<step command="Assert_Title"><![CDATA[${wet-secret} / Assert Content]]></step>
	<step command="Comment"><![CDATA[more parts]]></step>
	<step command="Assert_Title"><![CDATA[Wetator, Assert, Content]]></step>
	<step command="Assert_Title"><![CDATA[Wetator, Content]]></step>
	<step command="Assert_Title"><![CDATA[W*tator, Co*t]]></step>
	<step command="Comment"><![CDATA[test errors]]></step>
	<step command="Assert_Fail"><![CDATA[Assert Title, Expected content(s) {not found} or [in wrong order]: 'Wetator\, Content\, [Assert]' (content: 'Wetator / Assert Content').]]><optionalParameter><![CDATA[Wetator, Content, Assert]]></optionalParameter></step>
	<step command="Assert_Fail"><![CDATA[Assert Title, Expected content(s) {not found} or [in wrong order]: '{wrong*}' (content: 'Wetator / Assert Content').]]><optionalParameter><![CDATA[wrong*]]></optionalParameter>
	</step>
</testcase>

=== Wetator/wetator/test/xml/set_upload.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput with name]]></step>
	<step command="Set"><![CDATA[inputFile_Name]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileNameTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileNameTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_Name, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput with id]]></step>
	<step command="Set"><![CDATA[inputFile_Id]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileIdTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileIdTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFileId_Name, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput with name and default]]></step>
	<step command="Set"><![CDATA[inputFile_Name_Value]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileNameValueTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileNameValueTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_Name_Value, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput with name and default; try to cleanup]]></step>
	<step command="Set"><![CDATA[inputFile_Name_Value]]></step>
	<step command="Click_On"><![CDATA[InputFileNameValueTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileNameValueTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_Name_Value, name, size, 0]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by label]]></step>
	<step command="Set"><![CDATA[InputFile Label]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLabelTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLabelTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_Label, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by layout directly before]]></step>
	<step command="Set"><![CDATA[InputFile LayoutLabel before]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLayoutBeforeTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLayoutBeforeTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_LayoutBefore, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by layout directly before formated]]></step>
	<step command="Set"><![CDATA[InputFile LayoutLabel before formated]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLayoutBeforeFormatedTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLayoutBeforeFormatedTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_LayoutBeforeFormated, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by layout at top]]></step>
	<step command="Set"><![CDATA[InputFile LayoutLabel at top]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLayoutTopTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLayoutTopTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_LayoutTop, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by layout at top formated]]></step>
	<step command="Set"><![CDATA[InputFile LayoutLabel at top formated]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLayoutTopFormatedTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLayoutTopFormatedTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_LayoutTopFormated, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by layout at left]]></step>
	<step command="Set"><![CDATA[InputFile LayoutLabel at left]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLayoutLeftTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLayoutLeftTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_LayoutLeft, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[set_upload.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Set Upload]]></step>
	<step command="Comment"><![CDATA[FileInput identified by layout at left formated]]></step>
	<step command="Set"><![CDATA[InputFile LayoutLabel at left formated]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[InputFileLayoutLeftFormatedTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, InputFileLayoutLeftFormatedTest, OK]]></step>
	<step command="Assert_Content"><![CDATA[File Upload, Upload Control, Values, inputFile_LayoutLeftFormated, name, test_file.txt, SampleData Content from ....]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
</testcase>

=== Wetator/wetator/test/xml/select_checkbox_after.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox with name]]></step>
	<step command="Select"><![CDATA[Select after this text, checkBox_after_Name]]></step>
	<step command="Click_On"><![CDATA[CheckBoxNameAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_Name, check_Name, CheckBoxNameAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox with id]]></step>
	<step command="Select"><![CDATA[Select after this text, checkBox_after_Id]]></step>
	<step command="Click_On"><![CDATA[CheckBoxIdAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBoxId_after_Name, check_Id, CheckBoxIdAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox with default selection]]></step>
	<step command="Select"><![CDATA[Select after this text, checkBox_after_NameChecked]]></step>
	<step command="Click_On"><![CDATA[CheckBoxNameValueAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_NameChecked, check_Checked, CheckBoxNameValueAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by label]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox Label]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLabelAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_Label, check_Label, CheckBoxLabelAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by layout directly after]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox LayoutLabel after]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLayoutAfterAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_LayoutAfter, check_LayoutAfter, CheckBoxLayoutAfterAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by layout directly after formated]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox LayoutLabel after formated]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLayoutAfterFormatedAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_LayoutAfterFormated, check_LayoutAfterFormated, CheckBoxLayoutAfterFormatedAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by layout at bottom]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox LayoutLabel at bottom]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLayoutBottomAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_LayoutBottom, check_LayoutBottom, CheckBoxLayoutBottomAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by layout at bottom formated]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox LayoutLabel at bottom formated]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLayoutBottomFormatedAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_LayoutBottomFormated, check_LayoutBottomFormated, CheckBoxLayoutBottomFormatedAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by layout at right]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox LayoutLabel at right]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLayoutRightAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_LayoutRight, check_LayoutRight, CheckBoxLayoutRightAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[select_after.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Select After]]></step>
	<step command="Comment"><![CDATA[CheckBox identified by layout at right formated]]></step>
	<step command="Select"><![CDATA[Select after this text, CheckBox LayoutLabel at right formated]]></step>
	<step command="Click_On"><![CDATA[CheckBoxLayoutRightFormatedAfterTest]]></step>
	<step command="Assert_Content"><![CDATA[GET Parameters, Key, Value, checkBox_after_LayoutRightFormated, check_LayoutRightFormated, CheckBoxLayoutRightFormatedAfterTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
</testcase>
