=== Wetator/wetator/test/xml/dtd/testcase.dtd
<!ELEMENT testcase (step+)>
<!ELEMENT step (#PCDATA | optionalParameter)*>
<!ELEMENT optionalParameter (#PCDATA)>

<!ATTLIST step
    command (Assert_Content | Assert_Deselected | Assert_Disabled | Assert_Selected | Assert_Set | Assert_Title | Click_After_Text | Click_On | Close_Window | Comment | Exec_Java | Go_Back | Mouse_Over | Open_Url | Select | Set | Use_Module) #REQUIRED
    comment (true | false) "false">

=== Wetator/wetator/test/xml/onkey.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[simple submit]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set input text]]></step>
	<step command="Set"><![CDATA[InputText]]><optionalParameter><![CDATA[i]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace onKeyDown(inputText); onKeyPress(inputText); onKeyUp(inputText); OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set input password]]></step>
	<step command="Set"><![CDATA[InputPassword]]><optionalParameter><![CDATA[i]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace onKeyDown(inputPassword); onKeyPress(inputPassword); onKeyUp(inputPassword); OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set textarea]]></step>
	<step command="Set"><![CDATA[Textarea]]><optionalParameter><![CDATA[i]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace onKeyDown(textarea); onKeyPress(textarea); onKeyUp(textarea); OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set file upload]]></step>
	<step command="Set"><![CDATA[Upload]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onKey event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[select single select]]></step>
	<step command="Select"><![CDATA[SingleSelect, option2]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onKey event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[select multiple select]]></step>
	<step command="Select"><![CDATA[MultipleSelect, option2]]></step>
	<step command="Select"><![CDATA[MultipleSelect, option1]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onKey event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[select checkbox]]></step>
	<step command="Select"><![CDATA[Checkbox]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onKey event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[select ratio button]]></step>
	<step command="Select"><![CDATA[Radio1]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onKey event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set input text with default]]></step>
	<step command="Set"><![CDATA[InputText with default]]><optionalParameter><![CDATA[i]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace onKeyDown(inputTextDefault); onKeyPress(inputTextDefault); onKeyUp(inputTextDefault); OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set input password with default]]></step>
	<step command="Set"><![CDATA[InputPassword with default]]><optionalParameter><![CDATA[i]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace onKeyDown(inputPasswordDefault); onKeyPress(inputPasswordDefault); onKeyUp(inputPasswordDefault); OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set textarea with default]]></step>
	<step command="Set"><![CDATA[Textarea with default]]><optionalParameter><![CDATA[i]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace onKeyDown(textareaDefault); onKeyPress(textareaDefault); onKeyUp(textareaDefault); OnKeyTest OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onkey.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnKey]]></step>
	<step command="Comment"><![CDATA[set file upload with default]]></step>
	<step command="Set"><![CDATA[Upload with default]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onKey event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key Value eventTrace OnKeyTest OK]]></step>
</testcase>

=== Wetator/wetator/test/xml/onfocus_onblur.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[simple submit]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[set input text]]></step>
	<step command="Set"><![CDATA[InputText]]><optionalParameter><![CDATA[testValue]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(inputText);onBlur(inputText);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[InputText try overwrite]]></step>
	<step command="Set"><![CDATA[InputPassword]]><optionalParameter><![CDATA[testValue]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(inputPassword);onBlur(inputPassword);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[set textarea]]></step>
	<step command="Set"><![CDATA[Textarea]]><optionalParameter><![CDATA[testValue]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(textarea);onBlur(textarea);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[set file upload]]></step>
	<step command="Set"><![CDATA[Upload]]><optionalParameter><![CDATA[misc_files/test_file.txt]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Comment"><![CDATA[not onFocus/onBlur event; this is the same the browser does]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[select single select]]></step>
	<step command="Select"><![CDATA[SingleSelect, option2]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(singleSelect);onBlur(singleSelect);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[select multiple select]]></step>
	<step command="Select"><![CDATA[MultipleSelect, option2]]></step>
	<step command="Select"><![CDATA[MultipleSelect, option1]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(multipleSelect);onBlur(multipleSelect);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[select checkbox]]></step>
	<step command="Select"><![CDATA[Checkbox]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(checkbox);onBlur(checkbox);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[select ratio button]]></step>
	<step command="Select"><![CDATA[Radio1]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(Radio1);onBlur(Radio1);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[select ratio button]]></step>
	<step command="Select"><![CDATA[Radio2]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(Radio2);onBlur(Radio2);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[onfocus_onblur.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / OnFocus OnBlur]]></step>
	<step command="Comment"><![CDATA[select ratio button]]></step>
	<step command="Select"><![CDATA[Radio1]]></step>
	<step command="Select"><![CDATA[Radio2]]></step>
	<step command="Click_On"><![CDATA[OK]]></step>
	<step command="Assert_Content"><![CDATA[Key, Value, eventTrace, onFocus(Radio1);onBlur(Radio1); onFocus(Radio2);onBlur(Radio2);, OnFocusOnBlurTest, OK]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
</testcase>

=== Wetator/wetator/test/xml/flow_simple_login.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[simple_login.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Simple Login]]></step>
	<step command="Comment"><![CDATA[set fields by label and press the button]]></step>
	<step command="Set"><![CDATA[User:]]><optionalParameter><![CDATA[WeT]]></optionalParameter></step>
	<step command="Set"><![CDATA[Password:]]><optionalParameter><![CDATA[tew]]></optionalParameter></step>
	<step command="Click_On"><![CDATA[Login]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Request Snoopy]]></step>
	<step command="Assert_Content"><![CDATA[POST Parameters, Key, Value, userid, WeT, password, tew]]></step>
</testcase>

=== Wetator/wetator/test/xml/assert_selected_radio.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton with name]]></step>
	<step command="Comment"><![CDATA[not possible]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton with id]]></step>
	<step command="Assert_Selected"><![CDATA[radioId1]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by label]]></step>
	<step command="Assert_Selected"><![CDATA[Radio2 Label]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout directly after]]></step>
	<step command="Assert_Selected"><![CDATA[RadioButton1 LayoutLabel after]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout directly after formated]]></step>
	<step command="Assert_Selected"><![CDATA[RadioButton1 LayoutLabel after formated]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout at right]]></step>
	<step command="Assert_Selected"><![CDATA[RadioButton2 LayoutLabel at right]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[assert_selected.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Selected]]></step>
	<step command="Comment"><![CDATA[RadioButton identified by layout at right formated]]></step>
	<step command="Assert_Selected"><![CDATA[RadioButton1 LayoutLabel right formated]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
</testcase>

=== Wetator/wetator/test/xml/exec_java.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">

<testcase>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticVoidMethodWithoutParams</step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticVoidMethodWithOneParam<optionalParameter>one</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticVoidMethodWithTwoParams<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticVoidMethodWithStringArray<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticVoidMethodWithVarargs<optionalParameter>one, two</optionalParameter></step>
    <step command="Comment"></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticMethodWithoutParams</step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticMethodWithOneParam<optionalParameter>one</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticMethodWithTwoParams<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticMethodWithStringArray<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.staticMethodWithVarargs<optionalParameter>one, two</optionalParameter></step>
    <step command="Comment"></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.voidMethodWithoutParams</step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.voidMethodWithOneParam<optionalParameter>one</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.voidMethodWithTwoParams<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.voidMethodWithStringArray<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.voidMethodWithVarargs<optionalParameter>one, two</optionalParameter></step>
    <step command="Comment"></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.methodWithoutParams</step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.methodWithOneParam<optionalParameter>one</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.methodWithTwoParams<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.methodWithStringArray<optionalParameter>one, two</optionalParameter></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.methodWithVarargs<optionalParameter>one, two</optionalParameter></step>
    <step command="Comment"></step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester().methodWithoutParams</step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester.methodWithoutParams()</step>
    <step command="Exec_Java">org.rbri.wet.commandset.ExecTester().methodWithoutParams()</step>
</testcase>

=== Wetator/wetator/test/xml/assert_selected_checkbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">

<testcase>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox with name</step>
    <step command="Assert_Selected">checkBox_Name</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox with id</step>
    <step command="Assert_Selected">checkBox_Id</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by label</step>
    <step command="Assert_Selected">CheckBox Label</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by layout directly after</step>
    <step command="Assert_Selected">CheckBox LayoutLabel after</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by layout directly after formated</step>
    <step command="Assert_Selected">CheckBox LayoutLabel after formated</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by layout at bottom</step>
    <step command="Assert_Selected">CheckBox LayoutLabel at bottom</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by layout at bottom formated</step>
    <step command="Assert_Selected">CheckBox LayoutLabel at bottom formated</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by layout at right</step>
    <step command="Assert_Selected">CheckBox LayoutLabel at right</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Open_Url">assert_selected.html</step>
    <step command="Assert_Title">Wetator / Assert Selected</step>
    <step command="Comment">CheckBox identified by layout at right formated</step>
    <step command="Assert_Selected">CheckBox LayoutLabel at right formated</step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Comment"></step>
    <step command="Comment"></step>
</testcase>

=== Wetator/wetator/test/xml/open_url.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Comment"><![CDATA[hard coded url]]></step>
	<step command="Open_Url"><![CDATA[http://www.gebit.de]]></step>
	<step command="Assert_Title"><![CDATA[GEBIT Solutions*]]></step>
	<step command="Comment"><![CDATA[with starting slash]]></step>
	<step command="Open_Url"><![CDATA[/assert_title.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Title]]></step>
	<step command="Comment"><![CDATA[without starting slash]]></step>
	<step command="Open_Url"><![CDATA[assert_title.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Title]]></step>
	<step command="Comment"><![CDATA[with dot]]></step>
	<step command="Open_Url"><![CDATA[./assert_title.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Title]]></step>
	<step command="Open_Url"><![CDATA[/./assert_title.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Title]]></step>
	<step command="Comment"><![CDATA[failure test]]></step>
	<step command="Assert_Fail"><![CDATA[Open Url, Opening url 'http://www.wetator.org/testcases/http_header.php?code=400' fails with server error '400 Bad Request for http://www.wetator.org/testcases/http_header.php?code=400'.]]><optionalParameter><![CDATA[http_header.php?code=400]]></optionalParameter></step>
	<step command="Assert_Fail"><![CDATA[Open Url, Opening url 'http://www.wetator.org/testcases/http_header.php?code=404' fails with server error '404 Not Found for http://www.wetator.org/testcases/http_header.php?code=404'.]]><optionalParameter><![CDATA[http_header.php?code=404]]></optionalParameter></step>
	<step command="Assert_Fail"><![CDATA[Open Url, Opening url 'http://www.wetator.org/testcases/http_header.php?code=500' fails with server error '500 Server Error for http://www.wetator.org/testcases/http_header.php?code=500'.]]><optionalParameter><![CDATA[http_header.php?code=500]]></optionalParameter></step>
	<step command="Comment"><![CDATA[final test]]></step>
	<step command="Open_Url"><![CDATA[assert_title.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / Assert Title]]></step>
	<step command="Comment"><![CDATA[test for unused parameter]]></step>
	<step command="Assert_Fail"><![CDATA[Open Url, The command 'Open Url' does not use the value 'unused' provided in column 2.]]><optionalParameter><![CDATA[assert_title.html]]></optionalParameter></step>
	<step command="Comment"><![CDATA[test for parameter support]]></step>
	<step command="Open_Url"><![CDATA[assert_title.html?secret=${wet}]]></step>
	<step command="Comment"><![CDATA[test for secret parts of the url]]></step>
	<step command="Open_Url"><![CDATA[assert_title.html?secret=${wet-secret}]]></step>
</testcase>

=== Wetator/wetator/test/xml/ajax_prototype.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "dtd/testcase.dtd">
<testcase>
	<step command="Open_Url"><![CDATA[ajax/prototype/prototype_ajax.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with Prototype]]></step>
	<step command="Comment"><![CDATA[add content via AJAX]]></step>
	<step command="Comment"><![CDATA[check the original content]]></step>
	<step command="Assert_Content"><![CDATA[Click to start AJAX demo...]]></step>
	<step command="Click_On"><![CDATA[Click to start AJAX demo]]></step>
	<step command="Comment"></step>
	<step command="Assert_Content"><![CDATA[This is some text transferred to the client via AJAX.]]></step>
	<step command="Comment"></step>
	<step command="Comment"></step>
	<step command="Open_Url"><![CDATA[ajax/prototype/prototype_ajax.html]]></step>
	<step command="Assert_Title"><![CDATA[Wetator / AJAX with Prototype]]></step>
	<step command="Comment"><![CDATA[change content via javascript loaded with AJAX]]></step>
	<step command="Comment"><![CDATA[check the original content]]></step>
	<step command="Assert_Content"><![CDATA[Click to start AJAX Javascript demo...]]></step>
	<step command="Click_On"><![CDATA[Click to start AJAX Javascript demo]]></step>
	<step command="Comment"></step>
	<step command="Assert_Content"><![CDATA[Click to start AJAX Javascript demo... Javascript Execute]]></step>
</testcase>
